// <auto-generated />
namespace DEMO.API.ApplicationInsights.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AgregandoCatalogos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregandoCatalogos));
        
        string IMigrationMetadata.Id
        {
            get { return "201802142208359_AgregandoCatalogos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
